name = "Touchy Hugo extended by Anastasia Protopapa"
license = "MIT"
licenselink = "https://github.com/protopapa/touchy-hugo/blob/master/LICENSE"
description = "A Hugo blog theme for single author. This theme is also 100% mobile responsive."
min_version = "0.58.0"